id = "rust-http-request"
name = "Rust Plugin making HTTP Request"
version = "0.0.0"
component = "${CARGO_TARGET_DIR:target}/wasm32-wasip2/debug/rust_http_request.wasm"
endpoint = "/rust/http-request/"

[build]
cmd = "cargo build --target wasm32-wasip2"
